### ISSUE TITLE
Utilisation de dossier temporaire

### ISSUE THREAD

**Issue by Succo** [Magalame/ProjetArte#1]
Hello

J'ai vu que tu utilisais "work" comme dossier temporaire de travail pour ton script.

Je te conseille de faire gaffe avec ça, en effet tu crée le dossier (sauf si il existe déjà) puis tu supprime sont contenu et à la fin tu supprimes complètement le dossier. SI quelqu'un avait déjà un dossier work avec des fichiers important dedans il risque d'être surpris.

Je te conseille de mettre une alerte et ne rien faire si le dossier existe déjà. Encore plus idéalement le dossier "/tmp" sert à ça personne n'est sensé y mettre de donnée pérenne car ce qui est dedans est nettoyé par l'OS et donc ne risque pas d'encombrer l'utilisateur si le script ne termine pas.

Projet sympa sinon.

**Comment by Magalame** [comment]
Très bonne remarque!
